In [11]:
def LU_doolittle(a):
    L=np.zeros(a.shape)
    U=np.zeros(a.shape)
    print("Assign diagonal elements of L=1")
    for i in range(0,a.shape[0]):
        L[i][i]=1
    for i in range(0,a.shape[0]):
        for j in range(i-1,a.shape[0]):
            if i<=j:
                summ=0
                print("i<=j")
                for k in range(0,i):
                    summ=summ+L[i][k]*U[k][j]
                print("summ="+str(summ))
                U[i][j]=a[i][j]-summ
                print("U[i][j]="+str(U[i][j]))
    for j in range(0,a.shape[0]):
        for i in range(j,a.shape[0]):
            if j<i:
                summ=0
                print("i>j")
                for k in range(0,j):
                    summ+=L[i][k]*U[k][j]
                print("summ="+str(summ))
                L[i][j]=(a[i][j]-summ)/U[j][j]
                print("L[i][j]="+str(L[i][j]))
    return L,U

In [12]:
import numpy as np
import math

In [13]:
A=np.array([[2,7],[3,-1]])
L,U=LU_doolittle(A)

Assign diagonal elements of L=1
i<=j
summ=0
U[i][j]=2.0
i<=j
summ=0
U[i][j]=7.0
i<=j
summ=0.0
U[i][j]=-1.0
i>j
summ=0
L[i][j]=1.5


In [14]:
print(L)

[[1.  0. ]
 [1.5 1. ]]


In [15]:
print(U)

[[ 2.  7.]
 [ 0. -1.]]


In [26]:
a=np.array([[1,2,3],[3,4,6]])
print(a)

[[1 2 3]
 [3 4 6]]


In [28]:
x=a[0,:]
print(x)

[1 2 3]


In [29]:
a[0,:]=a[1,:]
print(a)

[[3 4 6]
 [3 4 6]]


In [30]:
print(x)

[3 4 6]


In [27]:
a=np.array(a)